application: ahoy-twilio-workshop
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico
  
  
twilio_sid: '*****************'
twilio_token: '**********'
twilio_from: '********'
twilio_to: 'Number to send SMS along with ountry code'
uptime_key: 'u12345-badbeef0123456789'
